[package]
name = "storage-service"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }
types = { path = "../types" }
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
